import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { FeatureFlagsServerProvider } from "@/shared/hooks/useFeatureFlagsServerActions";
import { NotificationProvider } from "@/shared/providers/NotificationProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FeatureFlagsServerProvider>
          <NotificationProvider
            theme="system"
            visibleToasts={5}
            config={{
              position: "top-right",
              richColors: true,
              closeButton: true,
              dismissible: true,
              pauseWhenPageIsHidden: true,
            }}
          >
            {children}
          </NotificationProvider>
        </FeatureFlagsServerProvider>
      </body>
    </html>
  );
}
